server:
  compression:
    enabled: true
  # Default port
  port: 8080
  # Enable graceful shutdown - Server will wait for active request to finish
  shutdown: graceful
  tomcat:
    mbeanregistry:
      enabled: true
spring:
  application:
    name: elastic-search-sample
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: mhsj6S4eCTzb7lvlnISbCrKn
    repositories:
      enabled: true
  # Time to wait for active requests to finish during the shutdown
  lifecycle:
    timeout-per-shutdown-phase: 20s
# Swagger
springdoc:
  api-docs:
    path: /v3/api-doc
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui
